// Bootstrap and lifecycle management for the disposable local PostgreSQL
// cluster that automated tests run against.
//
// WHY A SECOND CLUSTER: this machine's PostgreSQL 17 Windows service
// (postgresql-x64-17, port 5432) is password-protected and shared; production
// lives on Supabase. Tests need a PostgreSQL server that (a) we fully own,
// (b) can be reset without asking anyone, and (c) physically cannot be the
// production database. This script initializes a dedicated cluster under
// %USERPROFILE%\.ticketing-test-pg, listening ONLY on 127.0.0.1:5433 — a
// different process from the installed service and a different machine from
// Supabase. The cluster is disposable: delete the folder, run
// `npm run test:pg:up`, and it is rebuilt from scratch.
//
// This module is infrastructure, not a test suite. CLI (also wired up as
// npm run test:pg:up / test:pg:down / test:pg:status):
//   node scripts/lib/testpg.js up      initialize (if needed) + start + create the base DB
//   node scripts/lib/testpg.js down    stop the cluster
//   node scripts/lib/testpg.js status  report where it is and whether it runs
//
// scripts/lib/testdb.js reuses ensureRunningForTest() so an individual suite
// auto-starts an already-initialized cluster (e.g. after a reboot) but never
// initializes or stops one on its own.

const { execFileSync } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');

const CLUSTER_ROOT = path.join(os.homedir(), '.ticketing-test-pg');
const DATA_DIR = path.join(CLUSTER_ROOT, 'data');
const MARKER_FILE = path.join(CLUSTER_ROOT, 'cluster.json');
const LOG_FILE = path.join(CLUSTER_ROOT, 'server.log');

// The port is chosen once at initialization time and stored in the marker and
// in postgresql.conf. 5433 keeps clear of the installed service on 5432.
const DEFAULT_PORT = 5433;
const BASE_DATABASE = 'ticketing_test';
const PG_USER = 'postgres';

// server/.env.test is written by `up()` when a fresh cluster is initialized so
// TEST_DATABASE_URL and the cluster's actual credentials can never drift apart.
const SERVER_DIR = path.join(__dirname, '..', '..');
const ENV_TEST_FILE = path.join(SERVER_DIR, '.env.test');
const ENV_TEST_MANAGED_MARKER = '# managed-by: ticketing-test-pg-bootstrap';

const EXE_SUFFIX = process.platform === 'win32' ? '.exe' : '';
const NEEDED_BINARIES = ['psql', 'pg_ctl', 'pg_isready', 'initdb'].map((b) => b + EXE_SUFFIX);

function findPgBinDir() {
  const candidates = [];
  if (process.platform === 'win32') {
    const root = 'C:\\Program Files\\PostgreSQL';
    if (fs.existsSync(root)) {
      for (const entry of fs.readdirSync(root)) candidates.push(path.join(root, entry, 'bin'));
    }
  }
  // One-line-package installs (homebrew, apt, ...) already have the binaries on PATH.
  for (const dir of (process.env.PATH || '').split(path.delimiter)) candidates.push(dir);

  for (const dir of candidates) {
    if (dir && NEEDED_BINARIES.every((b) => fs.existsSync(path.join(dir, b)))) return dir;
  }
  throw new Error(
    'PostgreSQL client binaries not found (need psql, pg_ctl, pg_isready, initdb).\n' +
      'Install PostgreSQL locally, or add its bin directory to PATH.'
  );
}

function bin(name) {
  return path.join(findPgBinDir(), name + EXE_SUFFIX);
}

function run(file, args, opts = {}) {
  return execFileSync(file, args, { encoding: 'utf8', timeout: 180000, ...opts });
}

function readMarker() {
  try {
    return JSON.parse(fs.readFileSync(MARKER_FILE, 'utf8'));
  } catch {
    return null;
  }
}

function pgMajorVersion() {
  const out = run(bin('initdb'), ['--version']);
  const m = out.match(/\(PostgreSQL\)\s+(\d+)/);
  if (!m) throw new Error(`Cannot parse initdb version output: ${out.trim()}`);
  return Number(m[1]);
}

function pgIsReady(port) {
  try {
    run(bin('pg_isready'), ['-h', '127.0.0.1', '-p', String(port)]);
    return true;
  } catch {
    return false;
  }
}

function isLoopbackHost(hostname) {
  const h = String(hostname || '').toLowerCase();
  return h === '127.0.0.1' || h === '::1' || h === 'localhost';
}

// Load server/.env.test without overriding anything already in the environment
// (same semantics as dotenv, which the application uses for server/.env).
function loadEnvTest() {
  try {
    require('dotenv').config({ path: ENV_TEST_FILE });
  } catch {
    /* dotenv always present as an app dependency; nothing to do if not */
  }
}

function writeEnvTest(password, port) {
  let existing = '';
  try {
    existing = fs.readFileSync(ENV_TEST_FILE, 'utf8');
  } catch {
    /* will be created */
  }
  if (existing && !existing.includes(ENV_TEST_MANAGED_MARKER)) {
    throw new Error(
      `${ENV_TEST_FILE} exists but was not generated by this bootstrap (no "${ENV_TEST_MANAGED_MARKER}" marker).\n` +
        'Refusing to overwrite it. Delete the file if it is stale, then re-run this command.'
    );
  }
  const body = [
    ENV_TEST_MANAGED_MARKER,
    '# Test-only database credentials. NEVER committed (gitignored) and never',
    '# read by the application: only scripts/lib/testdb.js loads this file.',
    '# The cluster is disposable; regenerate both it and this file with',
    '#   npm run test:pg:up',
    `TEST_DATABASE_URL="postgresql://${PG_USER}:${password}@127.0.0.1:${port}/${BASE_DATABASE}"`,
    '',
  ].join('\n');
  fs.writeFileSync(ENV_TEST_FILE, body);
}

// Initialize a brand-new cluster. The caller has verified DATA_DIR does not
// exist. Returns the generated password (also stored into .env.test).
function initCluster(port) {
  const password = crypto.randomBytes(24).toString('hex');
  fs.mkdirSync(CLUSTER_ROOT, { recursive: true });
  const pwFile = path.join(CLUSTER_ROOT, 'initdb-password.tmp');
  fs.writeFileSync(pwFile, password + '\n');
  try {
    run(bin('initdb'), [
      '-D', DATA_DIR,
      '-U', PG_USER,
      '-A', 'scram-sha-256',
      '--pwfile=' + pwFile,
      '-E', 'UTF8',
      '--no-locale',
    ]);
  } finally {
    fs.unlinkSync(pwFile);
  }

  // Bind to IPv4 loopback only and pin the port, so the cluster's identity is
  // fully recorded in its own config rather than depending on start flags.
  fs.appendFileSync(
    path.join(DATA_DIR, 'postgresql.conf'),
    `\n# ticketing test cluster (scripts/lib/testpg.js)\nlisten_addresses = '127.0.0.1'\nport = ${port}\n`
  );

  const marker = {
    port,
    pgVersion: pgMajorVersion(),
    user: PG_USER,
    baseDatabase: BASE_DATABASE,
    createdAt: new Date().toISOString(),
  };
  fs.writeFileSync(MARKER_FILE, JSON.stringify(marker, null, 2));
  writeEnvTest(password, port);
  return marker;
}

function startCluster() {
  console.log(`Starting test PostgreSQL cluster on 127.0.0.1 (log: ${LOG_FILE}) ...`);
  // stdio MUST be ignored here, never piped: on Windows the detached
  // postgres.exe inherits pg_ctl's pipe handles, and spawnSync would then wait
  // for pipe EOF that never arrives even though pg_ctl itself has exited.
  run(bin('pg_ctl'), ['-D', DATA_DIR, '-l', LOG_FILE, '-w', 'start'], { stdio: 'ignore' });
}

// Swap the database part of a PostgreSQL URL — used to reach the cluster's
// maintenance database ("postgres") for instance-level checks and DDL.
function adminUrlOf(url) {
  return url.replace(/\/[^/?]+(\?.*)?$/, '/postgres');
}

// Keep credentials out of console output and error messages.
function redact(url) {
  return String(url).replace(/:\/\/([^:/@]+):[^@/]+@/, '://$1:<redacted>@');
}

// Defensive identity check: make sure the server answering on the marker port
// is really THIS cluster and not some other PostgreSQL that happens to occupy
// the port (or a stale marker). Auth failures get a targeted explanation.
function verifyIdentity(testUrl, marker) {
  try {
    const dataDir = run(bin('psql'), [adminUrlOf(testUrl), '-tAc', 'SHOW data_directory']).trim();
    const norm = (p) => path.resolve(p).toLowerCase().replace(/[\\/]+$/, '');
    if (norm(dataDir) !== norm(DATA_DIR)) {
      throw new Error(
        `Port ${marker.port} is answered by a different PostgreSQL instance (data dir: ${dataDir}).\n` +
          `Refusing to run tests against it. Free the port or re-initialize the test cluster.`
      );
    }
  } catch (err) {
    if (String(err.message).includes('different PostgreSQL')) throw err;
    throw new Error(
      `Cannot authenticate to the test cluster with TEST_DATABASE_URL.\n` +
        `If server/.env.test was deleted or edited, delete the disposable cluster at\n` +
        `${CLUSTER_ROOT} and re-run "npm run test:pg:up".\n` +
        `Underlying error: ${redact(err.message)}`
    );
  }
}

function ensureBaseDatabase(testUrl) {
  const adminUrl = testUrl.replace(/\/[^/?]+(\?.*)?$/, '/postgres');
  const db = readMarker().baseDatabase;
  const exists = run(bin('psql'), [adminUrl, '-tAc', `SELECT 1 FROM pg_database WHERE datname = '${db}'`]).trim();
  if (!exists) run(bin('psql'), [adminUrl, '-v', 'ON_ERROR_STOP=1', '-c', `CREATE DATABASE "${db}"`]);
}

/**
 * Make sure the managed cluster is initialized (never done here — see up())
 * and running, and that the server on the marker port is really our cluster.
 * No-op unless TEST_DATABASE_URL points at a loopback host on the marker port,
 * so a test setup pointed at some other dedicated test server is untouched.
 *
 * @param {string} testUrl  resolved TEST_DATABASE_URL
 */
function ensureRunningForTest(testUrl) {
  const marker = readMarker();
  if (!marker) return;
  let parsed;
  try {
    parsed = new URL(testUrl);
  } catch {
    return;
  }
  if (!isLoopbackHost(parsed.hostname)) return;
  if (Number(parsed.port) !== marker.port) return;

  if (!pgIsReady(marker.port)) startCluster();
  verifyIdentity(testUrl, marker);
}

/* ------------------------------------------------------------------ CLI --- */

function up() {
  const marker = readMarker();
  if (!marker) {
    if (fs.existsSync(DATA_DIR)) {
      throw new Error(
        `${DATA_DIR} exists but ${MARKER_FILE} is missing — not a recognizable test cluster.\n` +
          'Inspect and remove that directory manually, then re-run.'
      );
    }
    const port = Number(process.env.TESTPG_PORT) || DEFAULT_PORT;
    console.log(`Initializing a fresh disposable PostgreSQL cluster in ${DATA_DIR} (port ${port}) ...`);
    initCluster(port);
  }

  const m = readMarker();
  const currentMajor = pgMajorVersion();
  if (currentMajor !== m.pgVersion) {
    throw new Error(
      `Test cluster was initialized with PostgreSQL ${m.pgVersion} but the installed binaries are ${currentMajor}.\n` +
        `Delete ${CLUSTER_ROOT} and re-run "npm run test:pg:up" to rebuild it (it is disposable).`
    );
  }

  loadEnvTest();
  const testUrl = process.env.TEST_DATABASE_URL;
  if (!testUrl) {
    throw new Error(
      `TEST_DATABASE_URL is not set. ${ENV_TEST_FILE} should define it — re-run "npm run test:pg:up".`
    );
  }

  if (!pgIsReady(m.port)) startCluster();
  verifyIdentity(testUrl, m);
  ensureBaseDatabase(testUrl);

  console.log(`Test cluster is ready:`);
  console.log(`  data dir : ${DATA_DIR}`);
  console.log(`  endpoint : 127.0.0.1:${m.port} (loopback only)`);
  console.log(`  base DB  : ${m.baseDatabase}`);
  console.log(`  env file : ${ENV_TEST_FILE}`);
}

function down() {
  const marker = readMarker();
  if (!marker) {
    console.log('No test cluster is initialized; nothing to stop.');
    return;
  }
  if (!pgIsReady(marker.port)) {
    console.log('Test cluster is not running.');
    return;
  }
  run(bin('pg_ctl'), ['-D', DATA_DIR, '-m', 'fast', '-w', 'stop']);
  console.log('Test cluster stopped.');
}

function status() {
  const marker = readMarker();
  if (!marker) {
    console.log(`No test cluster initialized (${CLUSTER_ROOT} has no marker). Run: npm run test:pg:up`);
    return;
  }
  const running = pgIsReady(marker.port);
  console.log(`Test cluster : ${CLUSTER_ROOT}`);
  console.log(`PostgreSQL   : ${marker.pgVersion}, port ${marker.port}, user ${marker.user}`);
  console.log(`Running      : ${running ? 'yes' : 'no'}`);
  loadEnvTest();
  if (running && process.env.TEST_DATABASE_URL) {
    try {
      verifyIdentity(process.env.TEST_DATABASE_URL, marker);
      console.log('Identity     : verified (data dir matches, TEST_DATABASE_URL authenticates)');
    } catch (err) {
      console.log(`Identity     : PROBLEM — ${err.message.split('\n')[0]}`);
    }
  }
  console.log(`TEST_DATABASE_URL: ${process.env.TEST_DATABASE_URL ? redact(process.env.TEST_DATABASE_URL) : '(not set — see server/.env.test)'}`);
}

module.exports = {
  CLUSTER_ROOT,
  DATA_DIR,
  ensureRunningForTest,
  psqlPath: () => bin('psql'),
};

if (require.main === module) {
  const cmd = process.argv[2];
  try {
    if (cmd === 'up') up();
    else if (cmd === 'down') down();
    else if (cmd === 'status') status();
    else {
      console.log('Usage: node scripts/test-pg.js [up|down|status]');
      process.exitCode = cmd ? 1 : 0;
    }
  } catch (err) {
    console.error(`ERROR: ${err.message}`);
    process.exitCode = 1;
  }
}
